### ISSUE TITLE
YAML Front Matter

### ISSUE THREAD

**Issue by prettydiff** [Unibeautify/sparser#72]
https://github.com/Glavin001/atom-beautify/issues/861

https://jekyllrb.com/docs/front-matter/

```yaml
---
# Only the main Sass file needs front matter (the dashes are enough)
---
@charset "utf-8"; // Our variables
$base-font-family: "Avenir Next", "Helvetica Neue", Helvetica, Arial, sans-serif;
$base-font-size: 16px;
$base-font-weight: 400;
$small-font-size: $base-font-size * .875;
$base-line-height: 1.5;
$spacing-unit: 30px;
$text-color: #111;
$background-color: #fdfdfd;
$brand-color: #5694f1;
$grey-color: #828282;
$grey-color-light: lighten($grey-color, 40%);
$grey-color-dark: darken($grey-color, 25%); // Width of the content area
$content-width: 800px;
$on-palm: 600px;
$on-laptop: 800px; // Use media queries like this:
// @include media-query($on-palm) {
//     .wrapper {
//         padding-right: $spacing-unit / 2;
//         padding-left: $spacing-unit / 2;
//     }
// }

@mixin media-query($device) {
    @media screen and (max-width: $device) {
        @content;
    }
}
// Import partials from `sass_dir` (defaults to `_sass`)
@import "base", "layout", "syntax-highlighting";
```

I need to fix the top YAML comment.  I can also auto-detect this as YAML Front Matter by checking for the YAML comment at the top after the code sample is identified as a CSS variant.
